### PR TITLE
Use npm prepublish instead of committing dist files

### PR DESCRIPTION
**Pull request by acdlite**
I believe it's best practice to use the npm prepublish hook instead of committing generated build files. (One exception I can think of is when you want to provide a browser build for non-npm consumers.) This reduces bloat in the repo and reduces the likelihood that you'll forget to build before publishing.

### CODE REVIEW

**Comment by gaearon** [comment]
If `dist-modules` is in `.gitignore`, would it still be part of the published package? I think folks usually keep it somewhere, e.g. https://github.com/rackt/react-router/tree/master/build/npm

**Comment by acdlite** [comment]
Ah, I forgot to add .npmignore :)

It's really up to you. I prefer to leave generated files out of the repo for the reasons mentioned above.

**Comment by gaearon** [comment]
Totally agree, I just had no idea `.npmignore` exists. :-)

**Comment by gaearon** [comment]
Merged, thanks again!

**Comment by acdlite** [comment]
No problem. Psyched about this project!

**Pull request merged**
