### PR TITLE
Rewrite to Redux

### PR DESCRIPTION
**Pull request by gaearon**
Tracking my attempt to rewrite to Redux to solve issues like https://github.com/gaearon/react-dnd/issues/253.

### CODE REVIEW

**Comment by vkbansal** [comment]
AFAIK, I believe that this should have been a 2.0 release.

**Comment by gaearon** [comment]
Why? Public API hasn't changed. If there are bugs they need to be fixed in patch releases.

**Comment by vkbansal** [comment]
@gaearon Just a suggestion. You know better.

**Comment by gaearon** [comment]
React DnD and DnD Core follow semantic versioning.
Please see here: https://github.com/mojombo/semver/blob/master/semver.md#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Pull request merged**
